#  Copyright (C) Oncher App - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Oncher App Engineering Team <engineering.team@oncher.com>, 2021


# ======================================= .iss BUILDER ==========================================

def get_inno_config():
    import os
    from config_variables import _APP_NAME, _VERSION_NAME, _APP_ICON_PATH, _DIST_FOLDER_PATH

    _DIST_FOLDER_PATH = os.path.abspath(os.path.join('..', 'build_output', _DIST_FOLDER_PATH, _APP_NAME))

    _buffer_1 = r"""
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "%s"
#define MyAppVersion "%s"
#define MyAppPublisher "oncher.com"
#define MyAppURL "https://www.oncher.com"
#define MyAppExeName "Oncher.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{79E19D5A-A694-4F84-BC5B-45109D7C6E1F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputBaseFilename=oncher
SetupIconFile=%s
UninstallDisplayIcon={app}\{#MyAppExeName}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
    """ % (
        _APP_NAME, _VERSION_NAME, os.path.abspath(os.path.join(_DIST_FOLDER_PATH, 'static', 'images', _APP_ICON_PATH)))
    print(_buffer_1)
    # %s e.g: # I:\FivverProjects\ONCHER-APP\release\Oncher
    # first file is the exe then other bloody .pyd files

    _buffer_2 = r"""
[Files]"""

    # add files
    files_and_folders = os.listdir(_DIST_FOLDER_PATH)
    for f in files_and_folders:
        path  = os.path.join(_DIST_FOLDER_PATH, f)
        if os.path.isfile(path):
            # print(f)
            _buffer_2 += r"""
Source: "%s"; DestDir: "{app}"; Flags: ignoreversion""" % (path)

    for f in files_and_folders:
        path = os.path.join(_DIST_FOLDER_PATH, f)
        if os.path.isdir(path):
            # I:\FivverProjects\ONCHER-APP\release\Oncher\certifi
            # certifi
            # we can put "createallsubdirs" only for static here
            _buffer_2 += r"""
Source: "%s\*"; DestDir: "{app}\%s"; Flags: ignoreversion recursesubdirs createallsubdirs""" % (path, path.split("\\")[-1])
    print(_buffer_2)

get_inno_config()

